# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-08 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, default='', to='tags.Tag'),
        ),
    ]
