# Generated by Django 3.0.8 on 2021-02-07 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post_types', '0001_initial'),
        ('posts', '0002_auto_20210206_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='post_types.PostType'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(default='', max_length=350),
        ),
    ]
