# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-11 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
        ('endusers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='tags',
            field=models.ManyToManyField(blank=True, default='', related_name='_staff_tags_+', to='tags.StaffTag'),
        ),
        migrations.AddField(
            model_name='customer',
            name='parent_customer',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='endusers.Customer'),
        ),
        migrations.AddField(
            model_name='customer',
            name='tags',
            field=models.ManyToManyField(blank=True, default='', related_name='_customer_tags_+', to='tags.CustomerTag'),
        ),
    ]
