"""
Django settings for konnote project.

Generated by 'django-admin startproject' using Django 1.11.15.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '-!o!*#uuer)m8t06#0$7o7t5vc=f9j+3$1(r81)+mci(r6bz32'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['0.0.0.0']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_filters',
    'levels',
    'subjects',
    'chapters',
    'topics',
    'posts',
    'tags',
    'resources',
    'post_resources',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'konnote.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'konnote.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'

NUMBER_OF_CONCURRENT_SESSIONS = 1
THRESHOLD_NUMBER_OF_LOGIN_ATTEMPTS = 3
VERFICATION_MAXLENGTH = 6
CHAR_MAX_LENGTH = 50
TEXT_AREA_MAX_LENGTH = 250
MOBILE_MAX_LENGTH = 17
COLOR_MAX_LENGTH = 6
POSTAL_CODE_MAX_LENGTH = 6
DECIMAL_MAX_LENGTH = 10
DECIMAL_PLACES = 2
DECIMAL_DEFAULT = 2
VARIABLE = 4
SHORT_TEXT_LENGTH = 20

ACCOUNT_TYPES = (('Individual', 'Individual'),
                 ('Corporate', 'Corporate')
                 )
CUSTOMER_PHASE = (('Visitor', 'Visitor'),
                 ('Prospect', 'Prospect'),
                 ('Activate User', 'Activate User'),
                 ('Paying Customer', 'Paying Customer'),
                 ('Repeat Customer', 'Repeat Customer'),
                 )

SMS_NOTIFICATION_SETTING_OPTIONS = ((0, 'Off'),
                 (1, 'On')
                 )
EMAIL_NOTIFICATION_SETTING_OPTIONS = ((0, 'Off'),
                 (1, 'On')
                 )
ACCOUNT_STATUS_OPTIONS = ((0, 'Not Activated'),
                    (1, 'Activated'),
                    (2, 'Expired'),
                    (3, 'Dormant'),
                    (4, 'Pending Deletion'),
                    (5, 'Blocked'),
                    )
GAMIFICATION_OPTIONS = ((0, 'Off'),
                 (1, 'On')
                 )

VERIFICATION_OPTIONS = ((0, 'Not Verified'),
                 (1, 'Verified')
                 )

MOBILE_OPTIONS = ((0, 'Not Mobile Ready'),
                 (1, 'Mobile Ready')
                 )

STAFF_USER_ROLES = (
                    ('ADMIN', 'Administrator'), # Across Accounts, Full Access
                    ('MANAGEMENT', 'Management'), # Fortitude Management Staff
                    ('CUSTOMER CARE', 'Customer Care'), # Fortitude Staff + Customer Care
                 )

CUSTOMER_USER_ROLES = (
                    ('CUST ADMIN', 'Customer Administrator'), # Create Users within limit of Account Product
                    ('CUST STAFF', 'Customer Staff'),
                    ('CUSTOMER', 'Customer'),
                 )

COURSE_AVAILABILITY = ((0, 'Unavailable'),
                 (1, 'Available')
                 )

CUSTOM_WORKFLOWS = (
                (0, 'Unavailable'),
                (1, 'Available')
                 )

PROMOTION_TYPES = (
                (0, 'Percentage'),
                (1, 'Value')
                 )

ADVERTISEMENT_STATUS = ((0, 'Off'),
                 (1, 'On')
                 )

FINANCIAL_DURATION_IN_MONTHS = ((1, '1 Month'),
                (3, '1 Quarter'),
                (6, '1 Half'),
                (12, '1 Year'),
                 )


COUNTRIES_ONLY = [
    ('Kenya', 'Kenya'),
]

PAYMENT_METHOD = (
                ('M-Pesa', 'M-Pesa'),
                 )

DATE_FORMAT = "%Y-%m-%d"
TIME_FORMAT = "%H:%M:%S"
DATE_TIME_FORMAT = "%Y-%m-%d at %H:%M"

GENDER = [
    (0, 'Female'),
    (1, 'Male'),
]
