# Generated by Django 3.0.8 on 2021-02-06 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_tag_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='slug',
            new_name='slug_tag',
        ),
    ]
