# Generated by Django 3.0.8 on 2021-02-07 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0004_auto_20210206_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='slug_tag',
        ),
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default='best-practice', unique=True),
            preserve_default=False,
        ),
    ]
