# Generated by Django 3.0.8 on 2021-02-07 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0006_auto_20210207_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='slug',
        ),
    ]
